language: cpp
sudo: required
compiler:
  - gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-7
    - g++-7
before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt5-qmake qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
  - pip install --user cpp-coveralls
  - export CC="gcc-7"
  - export CXX="g++-7"
  - gcc --version
  - g++ --version
script:
  - ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
  - ln -s /usr/bin/g++-6 /usr/local/bin/g++
  - cd source
  - qmake -qt=qt5
  - make
  - ./ViajeFacil
after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
