language: cpp
compiler:
  - gcc
before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt5-qmake qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
  - pip install --user cpp-coveralls
script:
  - cd config/qt
  - qmake -qt=qt5
  - make
  - ./ViajeFacil
after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
